version: '3.8'
services:
  db:
    build:
      context: ../
      dockerfile: $PWD/docker/Dockerfile.pg
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - 'volume:/var/lib/postgresql/data'
    env_file:
      - ../.env
    ports:
      - '${DB_PORT:-5432}:5432'
volumes:
  volume: null